# These are supported funding model platforms

github: [splat1985]
patreon: splat1985
open_collective: splat1985
ko_fi: splat1985
tidelift: npm/splat1985
community_bridge: splat1985
liberapay: splat1985
issuehunt: splat1985
lfx_crowdfunding: splat1985
polar: splat1985
buy_me_a_coffee: splat1985
thanks_dev: splat1985
custom: ['https://www.patreon.com/c/splat1985']
